services:
  postgres:
    container_name: song_la_postgres
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - song-la

networks:
  song-la:
    name: song-la
    driver: bridge